
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush Jain
 */
public class Claimers extends javax.swing.JFrame {

    /**
     * Creates new form Claimers
     */
    public Claimers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rno = new javax.swing.JTextField();
        distribute = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        p = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JComboBox<>();
        Exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        result1 = new javax.swing.JMenu();
        claim = new javax.swing.JMenu();
        Penalty = new javax.swing.JMenu();
        overall = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 3, 60)); // NOI18N
        jLabel6.setText("Attendance Manager");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 520, -1));

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel7.setText("Claim Attendance");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 360, 60));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Enter Register No");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, 20));
        getContentPane().add(rno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 140, -1));

        distribute.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        distribute.setText("Search");
        distribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributeActionPerformed(evt);
            }
        });
        getContentPane().add(distribute, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Period Number Missed");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 190, 20));

        p.setEditable(true);
        p.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        p.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        p.setEnabled(false);
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 140, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Place At where you were present");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 250, 20));

        a.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SWO", "Student Council", "NCC", "CAPS" }));
        a.setEnabled(false);
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 140, -1));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        b2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        b2.setText("Claim");
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-1462755_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 490));

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        result1.setBackground(new java.awt.Color(0, 255, 255));
        result1.setForeground(new java.awt.Color(255, 0, 0));
        result1.setText("Details");
        result1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        result1.setOpaque(true);
        result1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                result1MenuSelected(evt);
            }
        });
        jMenuBar1.add(result1);

        claim.setBackground(new java.awt.Color(255, 0, 51));
        claim.setForeground(new java.awt.Color(0, 255, 255));
        claim.setText("Claim");
        claim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        claim.setOpaque(true);
        claim.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                claimMenuSelected(evt);
            }
        });
        jMenuBar1.add(claim);

        Penalty.setBackground(new java.awt.Color(0, 255, 255));
        Penalty.setForeground(new java.awt.Color(255, 0, 51));
        Penalty.setText("Penalty");
        Penalty.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Penalty.setOpaque(true);
        Penalty.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                PenaltyMenuSelected(evt);
            }
        });
        jMenuBar1.add(Penalty);

        overall.setBackground(new java.awt.Color(255, 0, 51));
        overall.setForeground(new java.awt.Color(0, 255, 255));
        overall.setText("Overall Details");
        overall.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        overall.setOpaque(true);
        overall.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                overallMenuSelected(evt);
            }
        });
        jMenuBar1.add(overall);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claimMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_claimMenuSelected
        Claimers a = new Claimers();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_claimMenuSelected

    private void PenaltyMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_PenaltyMenuSelected
        Penalty a = new Penalty();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PenaltyMenuSelected

    private void overallMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_overallMenuSelected
        overall a =new overall();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_overallMenuSelected

    private void distributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributeActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost"
                + ":3306/attendance","root","root");
            int q =Integer.parseInt(rno.getText());
            Statement st= c.createStatement();
            String s = "Select * from details where regno="+q+";";
            ResultSet rs = st.executeQuery(s);
            int qua=0;
            while(rs.next())
            {qua++;}
            if(qua>0)
            {   JOptionPane.showMessageDialog(this,"Data Found. Enter the Claim Details.");
                p.setEditable(true);
                a.setEditable(true);
                p.setEnabled(true);
                a.setEnabled(true);
                b2.setEnabled(true);}
            else
            {JOptionPane.showMessageDialog(this,"Data not Found. Enter Again");
             rno.setText("");
             rno.requestFocus(); }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());}                   // TODO add your handling code here:
    }//GEN-LAST:event_distributeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Exit a = new Exit();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Servicedetails a = new Servicedetails();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost"
                    + ":3306/attendance","root","root");
            int r = Integer.parseInt(rno.getText());
            int t = Integer.parseInt((String) p.getSelectedItem());
            String y = (String) a.getSelectedItem();
            Statement st= c.createStatement();
            String s = "Insert into claim values("+r+","+t+",'"+y+"');";
            String w = "Update details set Tclass = Tclass+1,Mclass=Mclass+1 where regno="+r+";";
            String e = "Update details set percent = (Aclass*100)/Tclass";
            st.executeUpdate(w);
            st.executeUpdate(e);
            int h = st.executeUpdate(s);
            if(h>0)
                {JOptionPane.showMessageDialog(this,"Record Saved Successfully");
                 rno.setText("");
                 p.setSelectedIndex(-1);
                 a.setSelectedIndex(-1);
                 p.setEditable(false);
                 a.setEditable(false);
                 p.setEnabled(false);
                 a.setEnabled(false);
                 b2.setEnabled(false);}
               else
                {JOptionPane.showMessageDialog(this,"Record not Saved");}
            }
            catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());}                      // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        rno.setText("");
        p.setSelectedIndex(-1);
        a.setSelectedIndex(-1);
        p.setEditable(false);
        a.setEditable(false);
        p.setEnabled(false);
        a.setEnabled(false);
        b2.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void result1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_result1MenuSelected
details a = new details();
this.dispose();
a.setVisible(true);
    }//GEN-LAST:event_result1MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Claimers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Claimers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Claimers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Claimers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Claimers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JMenu Penalty;
    private javax.swing.JComboBox<String> a;
    private javax.swing.JButton b2;
    private javax.swing.JButton back;
    private javax.swing.JMenu claim;
    private javax.swing.JButton clear;
    private javax.swing.JButton distribute;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu overall;
    private javax.swing.JComboBox<String> p;
    private javax.swing.JMenu result1;
    private javax.swing.JTextField rno;
    // End of variables declaration//GEN-END:variables
}
