
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush Jain
 */
public class details extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        mc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rno = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        distribute1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        result1 = new javax.swing.JMenu();
        claim = new javax.swing.JMenu();
        Penalty = new javax.swing.JMenu();
        overall = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Enter Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 20));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 3, 60)); // NOI18N
        jLabel6.setText("Attendance Manager");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 520, -1));

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel7.setText("Details");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, 60));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Enter Register No");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 20));
        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 140, -1));
        getContentPane().add(mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Total Classes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 160, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Classes Missed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 160, 20));
        getContentPane().add(rno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 140, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 140, -1));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        distribute1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        distribute1.setText("Enter");
        distribute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribute1ActionPerformed(evt);
            }
        });
        getContentPane().add(distribute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-1462755_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        result1.setBackground(new java.awt.Color(0, 255, 255));
        result1.setForeground(new java.awt.Color(255, 0, 0));
        result1.setText("Details");
        result1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        result1.setOpaque(true);
        result1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                result1MenuSelected(evt);
            }
        });
        jMenuBar1.add(result1);

        claim.setBackground(new java.awt.Color(255, 0, 51));
        claim.setForeground(new java.awt.Color(0, 255, 255));
        claim.setText("Claim");
        claim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        claim.setOpaque(true);
        claim.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                claimMenuSelected(evt);
            }
        });
        jMenuBar1.add(claim);

        Penalty.setBackground(new java.awt.Color(0, 255, 255));
        Penalty.setForeground(new java.awt.Color(255, 0, 51));
        Penalty.setText("Penalty");
        Penalty.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Penalty.setOpaque(true);
        Penalty.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                PenaltyMenuSelected(evt);
            }
        });
        jMenuBar1.add(Penalty);

        overall.setBackground(new java.awt.Color(255, 0, 51));
        overall.setForeground(new java.awt.Color(0, 255, 255));
        overall.setText("Overall Details");
        overall.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        overall.setOpaque(true);
        overall.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                overallMenuSelected(evt);
            }
        });
        jMenuBar1.add(overall);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Exit a = new Exit();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Servicedetails a = new Servicedetails();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void distribute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribute1ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost"
                    + ":3306/attendance","root","root");
            String n = name.getText();
            int r = Integer.parseInt(rno.getText());
            int t = Integer.parseInt(tc.getText());
            int m = Integer.parseInt(mc.getText());
            int a = t-m;
            double p = (a*100)/t;
            Statement st= c.createStatement();
            String s = "Insert into details values("+r+",'"+n+"',"+t+","+m
                    +","+a+","+p+")";
            int h = st.executeUpdate(s);
            if(h>0)
                {JOptionPane.showMessageDialog(this,"Record Saved Successfully"
                );
                 name.setText("");
                 rno.setText("");
                 tc.setText("");
                 mc.setText("");}
               else
                {JOptionPane.showMessageDialog(this,"Record not Saved");}
            }
            catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());}                   // TODO add your handling code here:
    }//GEN-LAST:event_distribute1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        name.setText("");
        rno.setText("");
        tc.setText("");
        mc.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void result1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_result1MenuSelected
details a = new details();
this.dispose();
a.setVisible(true);
    }//GEN-LAST:event_result1MenuSelected

    private void claimMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_claimMenuSelected
        Claimers a = new Claimers();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_claimMenuSelected

    private void PenaltyMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_PenaltyMenuSelected
        Penalty a = new Penalty();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PenaltyMenuSelected

    private void overallMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_overallMenuSelected
        overall a =new overall();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_overallMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JMenu Penalty;
    private javax.swing.JButton back;
    private javax.swing.JMenu claim;
    private javax.swing.JButton clear;
    private javax.swing.JButton distribute1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField mc;
    private javax.swing.JTextField name;
    private javax.swing.JMenu overall;
    private javax.swing.JMenu result1;
    private javax.swing.JTextField rno;
    private javax.swing.JTextField tc;
    // End of variables declaration//GEN-END:variables
}
