
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush Jain
 */
public class overall extends javax.swing.JFrame {

    /**
     * Creates new form overall
     */
    public overall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        distribute = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        mc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        result1 = new javax.swing.JMenu();
        claim = new javax.swing.JMenu();
        Penalty = new javax.swing.JMenu();
        overall = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 3, 60)); // NOI18N
        jLabel6.setText("Attendance Manager");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 510, -1));

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel7.setText("Overall Details");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 310, 60));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Enter Register No");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, 20));
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 140, -1));

        distribute.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        distribute.setText("Search");
        distribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributeActionPerformed(evt);
            }
        });
        getContentPane().add(distribute, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, -1, -1));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 120, 20));

        tc.setEditable(false);
        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 140, -1));

        mc.setEditable(false);
        getContentPane().add(mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Total Classes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 160, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Classes Missed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 20));

        n.setEditable(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 140, -1));

        m.setEditable(false);
        getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 140, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Classes Attended");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 160, 20));

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel9.setText("Claim Details");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 210, 60));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Attendance Percentage");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 180, 20));

        p.setEditable(false);
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 140, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("No. Of Classes Missed");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 200, 20));

        nme.setEditable(false);
        nme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmeActionPerformed(evt);
            }
        });
        getContentPane().add(nme, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 140, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Period Number", "Reason"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-1462755_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 590, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-1462755_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 530));

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        result1.setBackground(new java.awt.Color(0, 255, 255));
        result1.setForeground(new java.awt.Color(255, 0, 0));
        result1.setText("Details");
        result1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        result1.setOpaque(true);
        result1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                result1MenuSelected(evt);
            }
        });
        jMenuBar1.add(result1);

        claim.setBackground(new java.awt.Color(255, 0, 51));
        claim.setForeground(new java.awt.Color(0, 255, 255));
        claim.setText("Claim");
        claim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        claim.setOpaque(true);
        claim.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                claimMenuSelected(evt);
            }
        });
        jMenuBar1.add(claim);

        Penalty.setBackground(new java.awt.Color(0, 255, 255));
        Penalty.setForeground(new java.awt.Color(255, 0, 51));
        Penalty.setText("Penalty");
        Penalty.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Penalty.setOpaque(true);
        Penalty.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                PenaltyMenuSelected(evt);
            }
        });
        jMenuBar1.add(Penalty);

        overall.setBackground(new java.awt.Color(255, 0, 51));
        overall.setForeground(new java.awt.Color(0, 255, 255));
        overall.setText("Overall Details");
        overall.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        overall.setOpaque(true);
        overall.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                overallMenuSelected(evt);
            }
        });
        jMenuBar1.add(overall);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void result1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_result1MenuSelected
        details a = new details();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_result1MenuSelected

    private void claimMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_claimMenuSelected
        Claimers a = new Claimers();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_claimMenuSelected

    private void PenaltyMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_PenaltyMenuSelected
        Penalty a = new Penalty();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PenaltyMenuSelected

    private void overallMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_overallMenuSelected
        overall a =new overall();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_overallMenuSelected

    private void distributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributeActionPerformed
         try{
            Class.forName("java.sql.DriverManager");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost"
                + ":3306/attendance","root","root");
            int q =Integer.parseInt(r.getText());
            Statement st= c.createStatement();
            String s = "Select * from details where regno="+q+";";
            int y=0,tcl=0,mcl=0,acl=0;
            double qu=0;
            String nm="";
            ResultSet rs = st.executeQuery(s);
            while(rs.next())
            {int rg = rs.getInt("RegNo");
             nm = rs.getString("Name");
             tcl = rs.getInt("Tclass");
             mcl = rs.getInt("Mclass");
             acl = rs.getInt("Aclass");
             qu=rs.getDouble("percent");
             y++;}
            if(y>0)
            {n.setText(nm+"");
             tc.setText(""+tcl);
             m.setText(""+acl);
             p.setText(""+qu);
             mc.setText(""+mcl);
            
            DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
            int co=0;
            while(t.getRowCount()>0)
            {t.removeRow(0);}
            jTable1.setModel(t);
            String si = "Select * from claim where rno="+q;
            ResultSet rsi = st.executeQuery(si);
            while(rsi.next())
            {double ua = rsi.getInt("period");
             String bg = rsi.getString("reason");
             t.addRow(new Object[] {ua,bg});
             co++;}
            jTable1.setModel(t);
            nme.setText(""+co);
           if(co==0)
            {JOptionPane.showMessageDialog(this,"No claims for you.");}
           }
            else
            {JOptionPane.showMessageDialog(this,"Data not found.");
             r.setText("");}
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_distributeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
             r.setText("");
             n.setText("");
             tc.setText("");
             m.setText("");
             p.setText("");
             mc.setText("");
             nme.setText("");
            DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
            while(t.getRowCount()>0)
                {t.removeRow(0);}
                 jTable1.setModel(t);// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Servicedetails a = new Servicedetails();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Exit a = new Exit();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void nmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmeActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new overall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JMenu Penalty;
    private javax.swing.JButton back;
    private javax.swing.JMenu claim;
    private javax.swing.JButton clear;
    private javax.swing.JButton distribute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField m;
    private javax.swing.JTextField mc;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nme;
    private javax.swing.JMenu overall;
    private javax.swing.JTextField p;
    private javax.swing.JTextField r;
    private javax.swing.JMenu result1;
    private javax.swing.JTextField tc;
    // End of variables declaration//GEN-END:variables
}
