import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush Jain
 */
public class Penalty extends javax.swing.JFrame {

    /**
     * Creates new form Penalty
     */
    public Penalty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        distribute1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        result1 = new javax.swing.JMenu();
        claim = new javax.swing.JMenu();
        Penalty = new javax.swing.JMenu();
        overall = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 3, 60)); // NOI18N
        jLabel6.setText("Attendance Manager");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 520, -1));

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel7.setText("Penalty Calculator");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 380, 60));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Enter Register No");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 160, 20));
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 140, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Fine Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 20));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        distribute1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        distribute1.setText("Calculate");
        distribute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distribute1ActionPerformed(evt);
            }
        });
        getContentPane().add(distribute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Attendance Percenatge");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 190, 20));

        a.setEditable(false);
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 140, -1));

        f.setEditable(false);
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 140, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("( If attendance is less than 75% then there is no fine because you are not");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 570, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText(" eligible to write the exam )");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 230, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-1462755_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        result1.setBackground(new java.awt.Color(0, 255, 255));
        result1.setForeground(new java.awt.Color(255, 0, 0));
        result1.setText("Details");
        result1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        result1.setOpaque(true);
        result1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                result1MenuSelected(evt);
            }
        });
        jMenuBar1.add(result1);

        claim.setBackground(new java.awt.Color(255, 0, 51));
        claim.setForeground(new java.awt.Color(0, 255, 255));
        claim.setText("Claim");
        claim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        claim.setOpaque(true);
        claim.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                claimMenuSelected(evt);
            }
        });
        jMenuBar1.add(claim);

        Penalty.setBackground(new java.awt.Color(0, 255, 255));
        Penalty.setForeground(new java.awt.Color(255, 0, 51));
        Penalty.setText("Penalty");
        Penalty.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Penalty.setOpaque(true);
        Penalty.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                PenaltyMenuSelected(evt);
            }
        });
        jMenuBar1.add(Penalty);

        overall.setBackground(new java.awt.Color(255, 0, 51));
        overall.setForeground(new java.awt.Color(0, 255, 255));
        overall.setText("Overall Details");
        overall.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        overall.setOpaque(true);
        overall.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                overallMenuSelected(evt);
            }
        });
        jMenuBar1.add(overall);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Exit a = new Exit();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Servicedetails a = new Servicedetails();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void distribute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distribute1ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost"
                + ":3306/attendance","root","root");
            int q =Integer.parseInt(r.getText());
            Statement st= c.createStatement();
            String s = "Select * from details where regno="+q+";";
            double qu=0;
            int y=0;
            ResultSet rs = st.executeQuery(s);
            while(rs.next())
            {qu=rs.getDouble("percent");
             y++;}
            if(y>0)
            {a.setText(qu+"");
            if(qu>=85)
            {   JOptionPane.showMessageDialog(this,"There is no need to pay fine.");
                f.setText("0.0");}
            else if(qu>=75)
            {JOptionPane.showMessageDialog(this,"You need to pay fine.");
             double fine = (85-qu)*1000;
             f.setText(""+fine);}
            else
            {JOptionPane.showMessageDialog(this,"Sorry, You can't sit for the fine.Your attendance is less than 75%.");
             f.setText("0.0");}}
            else
            {JOptionPane.showMessageDialog(this,"Data not found.");
             r.setText("");
             f.setText("");
             a.setText("");
            }
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_distribute1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        a.setText("");
        r.setText("");
        f.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void result1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_result1MenuSelected
details a = new details();
this.dispose();
a.setVisible(true);
    }//GEN-LAST:event_result1MenuSelected

    private void claimMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_claimMenuSelected
        Claimers a = new Claimers();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_claimMenuSelected

    private void PenaltyMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_PenaltyMenuSelected
        Penalty a = new Penalty();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PenaltyMenuSelected

    private void overallMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_overallMenuSelected
        overall a =new overall();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_overallMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penalty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JMenu Penalty;
    private javax.swing.JTextField a;
    private javax.swing.JButton back;
    private javax.swing.JMenu claim;
    private javax.swing.JButton clear;
    private javax.swing.JButton distribute1;
    private javax.swing.JTextField f;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu overall;
    private javax.swing.JTextField r;
    private javax.swing.JMenu result1;
    // End of variables declaration//GEN-END:variables
}
